base: 'http://localhost/styleguide-demo-19'
baseVariants: {  }
errorHandling: {  }
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-us
    direction: ltr
    flag: us
    websiteTitle: ''
  -
    title: 'styleguide demo language danish'
    enabled: true
    base: /da/
    typo3Language: da
    locale: da_DK.UTF-8
    iso-639-1: da
    websiteTitle: ''
    navigationTitle: ''
    hreflang: ''
    direction: ''
    fallbackType: strict
    fallbacks: ''
    flag: dk
    languageId: 1
  -
    title: 'styleguide demo language german'
    enabled: true
    base: /de/
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    websiteTitle: ''
    navigationTitle: ''
    hreflang: ''
    direction: ''
    fallbackType: strict
    fallbacks: ''
    flag: de
    languageId: 2
  -
    title: 'styleguide demo language french'
    enabled: true
    base: /fr/
    typo3Language: fr
    locale: fr_FR.UTF-8
    iso-639-1: fr
    websiteTitle: ''
    navigationTitle: ''
    hreflang: ''
    direction: ''
    fallbackType: strict
    fallbacks: ''
    flag: fr
    languageId: 3
  -
    title: 'styleguide demo language spanish'
    enabled: true
    base: /es/
    typo3Language: es
    locale: es_ES.UTF-8
    iso-639-1: es
    websiteTitle: ''
    navigationTitle: ''
    hreflang: ''
    direction: ''
    fallbackType: strict
    fallbacks: ''
    flag: es
    languageId: 4
rootPageId: 19
routes: {  }
websiteTitle: 'styleguide demo 19'
