base: 'https://sig-screenshots-styleguide.ddev.site/'
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=5'
languages:
  -
    title: English
    enabled: true
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    websiteTitle: ''
    navigationTitle: ''
    hreflang: ''
    direction: ''
    flag: global
    languageId: 0
  -
    title: 'styleguide demo language danish'
    enabled: true
    base: /da/
    typo3Language: da
    locale: da_DA
    iso-639-1: da
    websiteTitle: ''
    navigationTitle: ''
    hreflang: ''
    direction: ''
    fallbackType: strict
    fallbacks: ''
    flag: dk
    languageId: 1
  -
    title: 'styleguide demo language french'
    enabled: true
    base: /fr/
    typo3Language: fr
    locale: fr_FR
    iso-639-1: fr
    websiteTitle: ''
    navigationTitle: ''
    hreflang: ''
    direction: ''
    fallbackType: strict
    fallbacks: ''
    flag: fr
    languageId: 3
  -
    title: 'styleguide demo language spanish'
    enabled: true
    base: /es/
    typo3Language: es
    locale: es_ES
    iso-639-1: es
    websiteTitle: ''
    navigationTitle: ''
    hreflang: ''
    direction: ''
    fallbackType: strict
    fallbacks: ''
    flag: es
    languageId: 4
  -
    title: 'styleguide demo language german'
    enabled: true
    base: /de/
    typo3Language: de
    locale: de_DE
    iso-639-1: de
    websiteTitle: ''
    navigationTitle: ''
    hreflang: ''
    direction: ''
    fallbackType: strict
    fallbacks: ''
    flag: de
    languageId: 2
rootPageId: 1
websiteTitle: ''
