version: '3.6'

services:
  chrome:
    container_name: ddev-${DDEV_SITENAME}-chrome
    image: selenium/standalone-chrome:4.0
    volumes:
      - /dev/shm:/dev/shm
    external_links:
      - ddev-router:$DDEV_HOSTNAME
