name: CI

on:
  push:
    branches:
      - main
      - debug


jobs:

  # this is useful var_dump output when developing
  some-context-vars:
    if: 0
    runs-on: ubuntu-latest
    steps:
      - name: Get branch or version name from repo (howto)
        id: get-bv_name
        run: |
          if [[ "$GITHUB_REF" == *"refs/tags"* ]]; then
            # v4.0.6 -> 4.0.6
            echo ::set-output name=branch_or_version::$(echo ${GITHUB_REF#refs/tags/} | sed 's/v//g')
          else
            # feature/something -> feature-something
            echo ::set-output name=branch_or_version::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')
          fi

      - name: Some vars
        run: |
          echo Echoing:
          echo 'github.event.action   :' ${{ github.event.action }}
          echo 'github.event.ref      :' ${{ github.event.ref }}
          echo 'github.event_name     :' ${{ github.event_name }}
          echo 'github.repository     :' ${{ github.repository }}
          echo 'github.sha            :' ${{ github.sha }}
          echo 'branch or version from GITHUB_REF:' ${{ steps.get-bv_name.outputs.branch_or_version }}
          echo 'GITHUB_REF            :' ${GITHUB_REF}
          echo 'GITHUB_REF#refs/heads/:' ${GITHUB_REF#refs/heads/}
          echo 'GITHUB_REF#refs/tags/ :' ${GITHUB_REF#refs/tags/}


  render-with-docker-container:
    runs-on: ubuntu-latest
    if: 1
    strategy:
      matrix:
        # online, offline
        mode: ['offline']
        manual: [['SIG-Screenshots', 'TYPO3-Documentation/SIG-Screenshots']]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ matrix.manual[1] }}
      - run: |
          mkdir -p Documentation-GENERATED-temp
          if [[ "${{ matrix.mode }}" = "offline" ]]; then
              echo '{"Overrides_cfg":{"html_theme_options":{"docstypo3org":""}}}' > Documentation-GENERATED-temp/jobfile.json
          fi
          if [[ "${{ matrix.mode }}" = "online" ]]; then
              echo '{"Overrides_cfg":{"html_theme_options":{"docstypo3org":"nonempty"}}}' > Documentation-GENERATED-temp/jobfile.json
          fi
      - name: docker run
        run: |
          docker run --rm --user=$(id -u):$(id -g) \
            -v $(pwd):/PROJECT:ro \
            -v $(pwd)/Documentation-GENERATED-temp:/RESULT \
            t3docs/render-documentation makehtml \
              -c make_singlehtml 0 \
              -c disable_include_files_check 1 \
              -c jobfile /RESULT/jobfile.json

      - name: Verify rendering result
        run: stat Documentation-GENERATED-temp/Result/project/0.0.0/index.html || stat Documentation-GENERATED-temp/Result/project/0.0.0/Index.html

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          # name: ${{ matrix.manual[0] }} (TYPO3 rendering example, mode ${{ matrix.mode }})
          name: ${{ matrix.manual[0] }}
          path: ./Documentation-GENERATED-temp/Result/project/0.0.0


  publish-gh-pages:
    needs: [render-with-docker-container]
    if: (github.event_name == 'push' && github.event.ref == 'refs/heads/main')
        || (github.event_name == 'push' && github.event.ref == 'refs/heads/debug')

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Download rendered docs
        uses: actions/download-artifact@v1
        with:
          name: SIG-Screenshots
          path: site
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          BRANCH: gh-pages
          FOLDER: site

